### ISSUE TITLE
Player Trading UI isn't updating icons on clients

### ISSUE THREAD

**Issue by Phardess** [vis2k/uMMORPG_CE#1]
**Versions (please complete the following information)**
 - Unity Version: 2018.4.12f1
 - uMMORPG CE Version: V2.5
 - Are you using a fresh uMMORPG version without any modifications? Yes

**Describe the bug**
Player Trading UI isn't updating icons on clients

**To Reproduce**
Steps to reproduce the behavior, please explain every single click that is needed:
1. Build client
2. Create player A on host
3. Create player B on client
4. Trade between these two players
5. On player A, drag one item from inventory on trading UI
6. Observe that item icon isn't updated on player B

**Expected behavior**
Icons should be updated with items icons on client too.

**System (please complete the following information):**
 - Windows 10

**Additional context**
The issue is coming from the fact that Player Inventory sync is set to owner, so clients can't get the inventory of another player.

**Comment by Bystreet** [comment]
Same problem.

**Comment by miwarnec** [comment]
fixed in latest version.
thanks for reporting guys.
