### ISSUE TITLE
Unable to create a new entity type because of circular dependencies.

### ISSUE THREAD

**Issue by charlouze** [vis2k/uMMORPG_CE#12]
When I started using uMMORPG CE, I noticed that it has a lot of circular dependencies. Even though i think it's a poor software design, it did not bother me at the time.

Today, I wanted to create a new entity. I declared a class that derived from Entity. I tryed to apply it to a game object but I couldn't because of those circular deps that points to Skill class that is abstract. Anyway, I created a skill class for my new entity type. I tried to apply it to my game object but then again... a dependency to the Entity class and this class is abstract.

I'm new to unity (but not to coding), so it's possible that I missed something.

**Comment by delgelato** [comment]
Some of them definitely can be not circular

Like, Monster requires MonsterSkill/Inventory, and MonsterInventory also requires Monster
In fact, maybe all the "RequireComponent" can be taken out, right? I mean, they should be well set up for the examples, and for those who wants to extend it (it's the point of CE?) should be able to do so.
Now, what will happen if i update and those Requires return? I have no idea...

**Comment by miwarnec** [comment]
It's usually better to duplicate the existing player/monster/npc prefab and then modify it.
But good point, will remove the circular requirements in next version

**Comment by miwarnec** [comment]
Fix is in V2.15
