### ISSUE TITLE
NetworkBehaviorNonAlloc.cachedName

### ISSUE THREAD

**Issue by delgelato** [vis2k/uMMORPG_CE#17]
If a NB calls get .name in Awake (anywhere before name is set), then it sets the name with (Clone), prohibiting proper name setup for that NB next time.

It's not really a bug as all the existing scripts all respects this "gotcha", but maybe can add a bit of warning in NBNA.name's \<summary> that explains to **not** call this in Awake

I was pulling my hair out a bit there... Just couldn't explain what's causing things to not work all of a sudden. Turned out a simple Debug.Log(name) in Awake was causing it..

**Comment by miwarnec** [comment]
can confirm

**Comment by miwarnec** [comment]
fixed in V2.21
