### ISSUE TITLE
No click-to-move animation controller provided

### ISSUE THREAD

**Issue by therealjohn** [vis2k/uMMORPG_CE#19]
The default (and only) animation controllers provided are for the physics based character controller. 

The docs state you can use click-to-move with the NavMesh style movement like in Classic, but an animation controller to match that is missing.

**Comment by jon-malave** [comment]
> The default (and only) animation controllers provided are for the physics based character controller.
> 
> The docs state you can use click-to-move with the NavMesh style movement like in Classic, but an animation controller to match that is missing.

No surprise once again... check my comments on your other issue. @vis2k is a con-artist, and expects people to kiss his ass because he created an asset that saves us X amount of hours, but yet provides shit support for one of the most popular assest on the Unity Asset Store! All the best to you and your game dev journey! Don't expect any help here...

**Comment by delgelato** [comment]
I wonder if linking to discord post works..
https://discord.com/channels/286563660544081931/656799760266821642/784632120622055464

But in case it doesn't:

Animation fix for player click navmesh move. Steps:

1. Duplicate the existing player prefab (warrior/archer/etc). Rename it to ur liking
2. Open PlayerSkills.cs and comment out this line at the top
//[RequireComponent(typeof(Movement))]
3. On this new player prefab, remove PlayerCharacterControllerMovement, then CharacterController2k, in that order
4. Add this script PlayerNavMeshMovement.cs
5. Assign the reference to movement in Player, PlayerSkills. Also assign several references in the PlayerNavMeshMovement too

Script is in .txt, so u gotta copy paste it i guess
[PlayerNavMeshMovement.txt](https://github.com/vis2k/uMMORPG_CE/files/5646472/PlayerNavMeshMovement.txt)

**Comment by miwarnec** [comment]
bugs were fixed.
documentation has a step by step guide now.
archer has click movement by default now.
