### ISSUE TITLE
Character position isn't correct after swimming

### ISSUE THREAD

**Issue by Phardess** [vis2k/uMMORPG_CE#2]
**Versions (please complete the following information)**
 - Unity Version: 2018.4.12f1
 - uMMORPG Version: V2.5
 - Are you using a fresh uMMORPG version without any modifications? Yes

**Describe the bug**
Character position isn't always correct after swimming

**To Reproduce**
No step-by-step 100% reproduction, but should be pretty easy to reproduce; Jump while going on the water, come back to the ground, jump, swim, and you should see the issue after few tries.

**Expected behavior**
Character shouldn't be flying above the ground after swimming

**Screenshots/Video**
![5746b69f4a16098a7a5693b6198e06e9](https://user-images.githubusercontent.com/5090572/74074372-0dd0b280-4a0e-11ea-9d54-8a9cf4cf4742.png)

**System (please complete the following information):**
 - Windows 10

**Comment by miwarnec** [comment]
fixed in V2.8, thanks!
