### ISSUE TITLE
Editor layout issue

### ISSUE THREAD

**Issue by VR-Architect** [vis2k/uMMORPG_CE#20]
FYI but not stopping from working with editor.

In the player entity prefab for warrior, on Player Charactor Controller Movement there is a small hiccup on the dropdown showing correctly. It is also In Player Equipment component. Looks like it may be array related. I am using 2020.2.16b

![image](https://user-images.githubusercontent.com/5250669/86612056-8916a000-bf7d-11ea-9c25-ee89e83ea2a2.png)

**Comment by miwarnec** [comment]
thanks for reporting.
looks fine in 2019.4.8:
![2020-08-28_15-50-36](https://user-images.githubusercontent.com/16416509/91570029-3edee900-e946-11ea-9a32-2bca6156fe5e.png)
PlayerCharacterController doesn't have a custom editor UI, so this was definitely a Unity bug. if you encounter it again, please report to Unity and share the case number here :)
