### ISSUE TITLE
DllNotFoundException  & NullReferenceException

### ISSUE THREAD

**Issue by yetouse** [vis2k/uMMORPG_CE#29]
Hello,

on a fresh asset import when playing in the editor i have theses errors ... but it works ;-)

But when Building (Client or server) it will not start.

**NullReferenceException: Object reference not set to an instance of an object**
Mirror.FallbackTransport.Available () (at Assets/uMMORPG/Plugins/Mirror/Runtime/Transport/FallbackTransport.cs:55)
Mirror.FallbackTransport.GetAvailableTransport () (at Assets/uMMORPG/Plugins/Mirror/Runtime/Transport/FallbackTransport.cs:45)
Mirror.FallbackTransport.Awake () (at Assets/uMMORPG/Plugins/Mirror/Runtime/Transport/FallbackTransport.cs:26)

**NullReferenceException: Object reference not set to an instance of an object**
Mirror.FallbackTransport.OnDisable () (at Assets/uMMORPG/Plugins/Mirror/Runtime/Transport/FallbackTransport.cs:37)

**DllNotFoundException: libuv**
libuv2k.Native.NativeMethods..cctor () (at Assets/uMMORPG/Plugins/libuv2k/libuv2k/Native/NativeHandles.cs:181)
Rethrow as TypeInitializationException: The type initializer for 'libuv2k.Native.NativeMethods' threw an exception.
libuv2k.Loop..ctor () (at Assets/uMMORPG/Plugins/libuv2k/libuv2k/Handles/Loop.cs:16)
Mirror.libuv2kTransport.Awake () (at Assets/uMMORPG/Plugins/libuv2k/MirrorTransport/libuv2kTransport.cs:55)

**Comment by yetouse** [comment]
unity 2019.4.11f1

**Comment by miwarnec** [comment]
fixed in latest libuv version.
will submit ummorpg CE with latest libuv very soon.
