### ISSUE TITLE
Package manager errors out on fresh project import

### ISSUE THREAD

**Issue by lukehoulihan** [vis2k/uMMORPG_CE#3]
Unity3d Version: 2019.3.5f1
uMMORPG CE Version: 2.9
When: Fresh asset store import on empty project.

This update appears to add a dependency that is incompatible with unity v2019.3.5f1 (and I would guess all 2019 builds). 

<img width="660" alt="Screen Shot 2020-03-24 at 6 29 19 PM" src="https://user-images.githubusercontent.com/16963820/77483586-e63b7b00-6dfe-11ea-8423-ae1c3cd58564.png">

The offending dependency is
`"com.unity.package-manager-ui": "2.0.3"`
Removing the package manager ui appears to resolve the issue.

**Comment by Ghetaldus** [comment]
Noticed this as well.
You can fix these errors by doing "Reset Packages to defaults".

![image](https://user-images.githubusercontent.com/30866474/77520495-95209b00-6e81-11ea-88ed-4a8e90b8e624.png)

**Comment by miwarnec** [comment]
@lukehoulihan that looks like a Unity bug. uMMORPG is still on 2018.3.6 so it's not even using any packages.

closing it for now. once 2019.4 LTS is released I will upgrade.
