### ISSUE TITLE
Pet exp not updating after kill like it should

### ISSUE THREAD

**Issue by delgelato** [vis2k/uMMORPG_CE#35]
I'll just paste from #help

SolistToday at 17:29
the question I needed to ask was that the experience my pet gains while alive is not passed to the item it is spawned from, why is this?
delgelatoToday at 17:50
Hmm, nice find

    // to save computations we don't sync to it all the time, it's enough to
    // sync in:
    // * OnDestroy when unsummoning the pet
    // * On experience gain so that level ups and exp are saved properly
    // * OnDeath so that people can't cheat around reviving pets
    // => after a server crash the health/mana might not be exact, but that's a
    //    good price to pay to save computations in each Update tick

It does say it should be doing on exp gain, but actually it's never called when that happens
U can try find this line in PlayerPetControl.OnKilledEnemy
And add to this:
            if(activePet != null)
            {
                activePet.experience.current += Experience.BalanceExpReward(((Monster)victim).rewardExperience, activePet.level.current, victim.level.current);
                activePet.SyncToOwnerItem();
            }

**Comment by miwarnec** [comment]
thanks for detailed report.
fix will be in V2.23 :)
