### ISSUE TITLE
After clean install can't reproduce what is seen in asset store video. (Multiple issues detected)

### ISSUE THREAD

**Issue by Skitosh** [vis2k/uMMORPG_CE#38]
**Versions (please complete the following information)**

- **Unity Version:** 2019.4.3f1
- **uMMORPG Version:** Downloaded from asset store 2 days ago. Where in the unity package do we get version number from ?
- **Are you using a fresh uMMORPG version without any modifications?** Yes
- **System:** Windows 10

**Describe the bug**
After clean install can't reproduce what is seen in asset store video. Asset store video https://assetstore.unity.com/packages/templates/systems/ummorpg-remastered-159401

Issues
- Gaurdian and architect skins do not load (See image "Guardian 1"). But you can still interact with them. "Bandit Boss" and Bandits show up ok. Appears as meshs and materials are missing for Guardian and Alchemist (See images Alchemist 1 a Alchemist 2).  _Can you advise on resolution ?_

- Attempting to run multiplayer to test dungeon. Build and run has triggered virus (malware) detection (See Virus 1). I have other mirror network unity project and they don't trigger virus notification. Something is triggering the prompt. Therefore why is a virus warning occurring and how does one test multi-player ? _Can you advise on resolution ?_

-To test the portal jump component without party. Sometimes a character needs to go into a solo instance. _Can you advise on resolution ?_

**To Reproduce**
Clean install

**Additional Info**

Would be great to have the advertised working product. 

Awaiting response
Skitosh

**Images**

Guardian 1
![image](https://user-images.githubusercontent.com/66407302/103961813-6aea6080-51a9-11eb-9ecb-7c52f2b81bea.png)

Alchemist 1
![image](https://user-images.githubusercontent.com/66407302/103962153-5d81a600-51aa-11eb-87b1-8866328e56c7.png)

Alchemist 2
![image](https://user-images.githubusercontent.com/66407302/103962189-75592a00-51aa-11eb-96bd-97d03c796a45.png)

Virus 1
![image](https://user-images.githubusercontent.com/66407302/103962921-244a3580-51ac-11eb-87ff-620540dd93c3.png)

**Comment by Joshua2504** [comment]
uMMORPG doesn't get detected as Virus by my Bitdefender.

But my NPCs are invisible too

**Comment by miwarnec** [comment]
hey guys, sorry took 6 months to look at this.
you can check all the source, it's pure Unity C#.
definitely not a virus, asset store team reviews every submission too :)

I think npc mesh issues were fixed a couple months ago.
closing this, let me know if it's still an issue.
