### ISSUE TITLE
No writer found for Skill. Use a type supported by Mirror or define a custom writer

### ISSUE THREAD

**Issue by Joshua2504** [vis2k/uMMORPG_CE#39]
Unity 2020.2.0f1
latest uMMORPG from asset store

This does not seem to affect the functionality of the game itself.

`No writer found for Skill. Use a type supported by Mirror or define a custom writer
UnityEngine.Logger:Log (UnityEngine.LogType,object)
Mirror.ILoggerExtensions:LogError (UnityEngine.ILogger,object) (at Assets/uMMORPG/Plugins/Mirror/Runtime/Logging/LogFactory.cs:82)
Mirror.NetworkWriter:Write<Skill> (Skill) (at Assets/uMMORPG/Plugins/Mirror/Runtime/NetworkWriter.cs:238)
Mirror.SyncList`1<Skill>:OnSerializeAll (Mirror.NetworkWriter) (at Assets/uMMORPG/Plugins/Mirror/Runtime/SyncList.cs:128)
Mirror.NetworkBehaviour:SerializeObjectsAll (Mirror.NetworkWriter) (at Assets/uMMORPG/Plugins/Mirror/Runtime/NetworkBehaviour.cs:685)
Mirror.NetworkBehaviour:OnSerialize (Mirror.NetworkWriter,bool) (at Assets/uMMORPG/Plugins/Mirror/Runtime/NetworkBehaviour.cs:607)
Mirror.NetworkIdentity:OnSerializeSafely (Mirror.NetworkBehaviour,Mirror.NetworkWriter,bool) (at Assets/uMMORPG/Plugins/Mirror/Runtime/NetworkIdentity.cs:929)
Mirror.NetworkIdentity:OnSerializeAllSafely (bool,Mirror.NetworkWriter,int&,Mirror.NetworkWriter,int&) (at Assets/uMMORPG/Plugins/Mirror/Runtime/NetworkIdentity.cs:989)
Mirror.NetworkServer:CreateSpawnMessagePayload (bool,Mirror.NetworkIdentity,Mirror.PooledNetworkWriter,Mirror.PooledNetworkWriter) (at Assets/uMMORPG/Plugins/Mirror/Runtime/NetworkServer.cs:1090)
Mirror.NetworkServer:SendSpawnMessage (Mirror.NetworkIdentity,Mirror.NetworkConnection) (at Assets/uMMORPG/Plugins/Mirror/Runtime/NetworkServer.cs:1059)
Mirror.NetworkServer:ShowForConnection (Mirror.NetworkIdentity,Mirror.NetworkConnection) (at Assets/uMMORPG/Plugins/Mirror/Runtime/NetworkServer.cs:905)
Mirror.NetworkConnection:AddToVisList (Mirror.NetworkIdentity) (at Assets/uMMORPG/Plugins/Mirror/Runtime/NetworkConnection.cs:165)
Mirror.NetworkIdentity:RebuildObservers (bool) (at Assets/uMMORPG/Plugins/Mirror/Runtime/NetworkIdentity.cs:1258)
NetworkProximityGridChecker:Update () (at Assets/uMMORPG/Scripts/NetworkProximityGridChecker.cs:117)
`

**Comment by miwarnec** [comment]
fixed in latest mirror / ummorpg version
