### ISSUE TITLE
Jumping/falling in water from horseback causes animation issues

### ISSUE THREAD

**Issue by lukehoulihan** [vis2k/uMMORPG_CE#4]
Unity3d Version: 2019.3.5f1
uMMORPG CE Version: 2.9
When: Fresh asset store import on empty project. 
Summon a mount and stand in water, then press jump.  The animation with attempt to transition between riding animations and swimming and then transition back to riding, ping-ponging until out of the water.
Entering water without jumping or falling works as expected.

<img width="660" alt="Screen Shot 2020-03-25 at 11 49 44 AM" src="https://user-images.githubusercontent.com/16963820/77556369-cfdd0000-6e8e-11ea-902c-fd5fa4ed0435.png">

**Comment by lukehoulihan** [comment]
Confirmed to happen on Unity3d Version: 2018.3.6f1 as well.

**Comment by miwarnec** [comment]
thanks, will take a look

**Comment by miwarnec** [comment]
looks like swimming with a horse doesn't work at all.
this works fine in uRPG though, so i missed something somewhere

**Comment by miwarnec** [comment]
fixed in V2.12
