### ISSUE TITLE
[Bug] WebGL build error (Plugin libuv.dll colliding)

### ISSUE THREAD

**Issue by Joshua2504** [vis2k/uMMORPG_CE#41]
Unity 2019.4.17f1
also tested on Unity 2020.2.0f1
latest uMMORPG

building webGL is impossible on both versions.

```
Plugin 'libuv.dll' is used from several locations:
 Assets/uMMORPG/Plugins/libuv2k/libuv_binaries/windows/x64/libuv.dll would be copied to <PluginPath>/libuv.dll
 Assets/uMMORPG/Plugins/libuv2k/libuv_binaries/windows/x86/libuv.dll would be copied to <PluginPath>/libuv.dll
Please fix plugin settings and try again.

UnityEditor.Modules.DefaultPluginImporterExtension:CheckFileCollisions(String)
UnityEditorInternal.PluginsHelper:CheckFileCollisions(BuildTarget)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

```

![](https://cdn.treudler.net/21/210109_022711_646-bJwn7-1042x233.png)

**Comment by Joshua2504** [comment]
Is it possible to get any update on this?

**Comment by Joshua2504** [comment]
A response would be appriciated, at least I paid money for this. I also send an E-Mail already and got no response. ... I see the developer doing commits on other repositories. Why did you block me on Discord?

**Comment by Joshua2504** [comment]
So... vis2k blocked me on discord after a simple message.

![](https://cdn.treudler.net/21/210113_010913_032-FgRec-843x204.png)

**Comment by miwarnec** [comment]
libuv was removed. fixed.
