### ISSUE TITLE
Update NetworkZone addon for Remastered

### ISSUE THREAD

**Issue by therealjohn** [vis2k/uMMORPG_CE#42]
The recommended solution is to use the old NetworkZone addon for uMMORPG classic. 

To support users who need to load different scenes, the old addon can be migrated to work for Remastered and newer versions of Mirror.

**Comment by miwarnec** [comment]
I don't think people really realize what it really means to run multiple instances.
you would have to:
- keep them all alive
- react if one of them dies
- transfer players between them
- support chat, guilds, etc. between them
- don't allow multiple logins
- and a lot more

I've got all my hands full just getting one scene to work properly. as in, easily 1-2 year's worth of work on my TODO list.
can't support scene instances too, sorry.
