### ISSUE TITLE
PlayerSkillbar not saving

### ISSUE THREAD

**Issue by delgelato** [vis2k/uMMORPG_CE#43]
This is from the Mirror bug here
https://github.com/vis2k/Mirror/issues/2533

OnDestroy is called after isClient/isServer is already resetted. I think on application quit/editor stop play, and maybe only on hostmode

But regardless, the fix is to change OnDestroy to OnStopClient in PlayerSkillbar.cs

**Comment by miwarnec** [comment]
thx for reporting

**Comment by miwarnec** [comment]
fixed in next version.
onstopclient is better. avoids the character selection workaround too.
