### ISSUE TITLE
[Bug] Portals Check level's twice on entry

### ISSUE THREAD

**Issue by NataIynn** [vis2k/uMMORPG_CE#44]
Bug: When entering a portal thats above user level, a message will be printed out into chat box twice everytime, instead of once.
Reproduce Steps: Create a portal with portal script, and set level requirement higher than normal.

![image](https://user-images.githubusercontent.com/28743579/110378717-893ed200-801b-11eb-8f67-fe1ee9f459b6.png)

**Comment by miwarnec** [comment]
nice find. 
OnTriggerEnter was called twice for a player. once for root collider and once for hip collider.
fixed in next version.
