### ISSUE TITLE
[Enhancement] Equipment Avatar Camera

### ISSUE THREAD

**Issue by NataIynn** [vis2k/uMMORPG_CE#45]
They're some enhancements that can be made to the Equipment Screen for higher FPS.

1. Disable the Avatar Camera on the equipment screen when the equipment screen is hidden. Currently the camera is always rendering your character + other players if they're near you. 
2. Other players render in your same camera for the equipment screen, which will lower your FPS if many players surrounding you while you're using the equipment screen.

**Comment by miwarnec** [comment]
nice find, didn't consider.
avatar camera is only enabled while UI is active in next version.

note that PlayerEquipment.avatarCamera needs to be reassigned in inspector once when upgrading manually.

as for not rendering other players: can't think of a good solution yet, where the solution wouldn't be worse than what we gain. maybe later.
