### ISSUE TITLE
Mirror asmdef file is missing reference to Libuv library

### ISSUE THREAD

**Issue by iamallama** [vis2k/uMMORPG_CE#46]
Created a brand new project and downloaded/imported the asset from the package manager. Immediately get error related to libuv2k.ResolveToIpv4 not being found. Selected Mirror asmdef file and added reference to libuv2k library and error goes away. This was with most recent version of uMMORPG Remastered downloaded right now.

**Comment by miwarnec** [comment]
libuv was removed. fixed.
