### ISSUE TITLE
Null ref on entering dungeon

### ISSUE THREAD

**Issue by delgelato** [vis2k/uMMORPG_CE#48]
**Describe the bug**
When entering dungeon instance, null ref on InstanceSpawnPoint.prefab
Checking in the inspector, they're all unassigned

**[IMPORTANT] How can we reproduce the issue, step by step:**
Clean install, form a party, enter dungeon in the rocks

**Expected behavior**
Enters dungeon

**Screenshots**
MissingReferenceException: The variable prefab of InstanceSpawnPoint doesn't exist anymore.
You probably need to reassign the prefab variable of the 'InstanceSpawnPoint' script in the inspector.
Instance.CreateInstance (Instance template, System.Int32 partyId) (at Assets/uMMORPG/Scripts/Instance.cs:253)
PortalToInstance.OnPortal (Player player) (at Assets/uMMORPG/Scripts/PortalToInstance.cs:25)
PortalToInstance.OnTriggerEnter (UnityEngine.Collider co) (at Assets/uMMORPG/Scripts/PortalToInstance.cs:57)

**Comment by miwarnec** [comment]
nice find.
fixed, thanks.

<img width="648" alt="2021-07-10_11-37-36@2x" src="https://user-images.githubusercontent.com/16416509/125150565-4892c900-e173-11eb-94f1-8f58387f139a.png">
