### ISSUE TITLE
Custom methods

### ISSUE THREAD

**Issue by Magic73** [vis2k/uMMORPG_CE#5]
Hi,
It is not exactly a problem, but a tip on how to allow the extension of some methods by the addons, avoiding having to modify the CORE sources.

I have seen how some addons are made. For example one of these requires to modify Entity's Damage method, to "overwrite" it following customizations.
This is a problem, because after each version update, one is obliged to report all the changes by hand (partial classes partially solve the problem, but when you have to intervene in this way .. you need to find an alternative solution).

In the example I have attached, I propose a solution that avoids that customizations require having to put hands to CORE files and methods too.

In the Entity class, for example, you could add a set of fields of type MethodInfo that go to look for the presence or not of the relative custom method.
The various methods are searched in the constructor, and then used.

Just a tip :)

I'm still trying to figure out if your package can fully meet my needs, but I can't deny that you've done an excellent job!

Here the link, it is a zip file with 4 .cs
[Link to example](https://www.magicstudio.eu/my/CustomTest.zip)

**Comment by Magic73** [comment]
Here another solution, with the use of Actions (maybe a better solution, with less reflection call on init):

CORE entities, within their constructor, should look for and then invoke a custom CustomInit method (which could be defined in the partial user custom class).
CORE entities should have a list of function fields, so each custom class within its CustomInit should assign these fields, so that within the CORE code these methods can be called in order to perform an external "override" of the main CORE method.

[Link to example](https://www.magicstudio.eu/my/CustomTest2.zip)

**Comment by miwarnec** [comment]
I think people don't really understand the addon system yet.
The goal is to use UnityEvents to hook into.
For example, Health has an OnEmpty event that you can use for OnDeath functions in all components.

Please try to use the events as far as possible - and if you need more then please let me know and I'll add more. This way you will never have to touch the core code.
