### ISSUE TITLE
Party Gold and Experience sharing dont work 

### ISSUE THREAD

**Issue by Assambra** [vis2k/uMMORPG_CE#6]
Version:
uMMORPG Components Edition Version 2.12
Unity Version 2019.3.9f1,

How to reproduce: 
Create a Windows build, Start one as host and the other one as client,
Create a Party and kill a Monster and only this character who kills the Monster get the Experience.
And only this party member who loot the corpse get the gold.
No sharing Gold and Experience in the party happend.

**Comment by Assambra** [comment]
Start and creating party.
![Start](https://user-images.githubusercontent.com/6276777/79266757-68680e00-7e98-11ea-94ff-e568636d745c.png)
After Monster kill.
![After](https://user-images.githubusercontent.com/6276777/79266766-6bfb9500-7e98-11ea-80ba-5cdb0791aee3.png)

**Comment by miwarnec** [comment]
checking

**Comment by miwarnec** [comment]
both exp sharing and gold sharing work, but you need to enable the settings in the party window:
![image](https://user-images.githubusercontent.com/16416509/81048581-e2e6e500-8ebc-11ea-8f86-3d9df2ab9032.png)

**Comment by Assambra** [comment]
Thank you very much and sorry. I probably missed the option.
