### ISSUE TITLE
Combat.cs Inverted function in blockChance & criticalchance properties

### ISSUE THREAD

**Issue by Nixou** [vis2k/uMMORPG_CE#9]
There is a mistake in theses properties. "Blockchance" call GetCriticalChanceBonus(). Same for "criticalChance"

Fix:

    // calculate block
    public float blockChance
    {
        get
        {
            // sum up manually. Linq.Sum() is HEAVY(!) on GC and performance (190 KB/call!)
            float bonus = 0;
            foreach (ICombatBonus bonusComponent in bonusComponents)
                bonus += bonusComponent.GetBlockChanceBonus();
            return baseBlockChance.Get(level.current) + bonus;
        }
    }

    // calculate critical
    public float criticalChance
    {
        get
        {
            // sum up manually. Linq.Sum() is HEAVY(!) on GC and performance (190 KB/call!)
            float bonus = 0;
            foreach (ICombatBonus bonusComponent in bonusComponents)
                bonus += bonusComponent.GetCriticalChanceBonus();
            return baseCriticalChance.Get(level.current) + bonus;
        }
    }

**Comment by miwarnec** [comment]
Fix in V2.13, thanks!
